name: filter_profanity
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.15.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

