name: filter_profanity
description: Dart package to recognize if provided string contains offensive words.

version: 1.0.2+1
homepage: https://github.com/sergiyvergun/filter_profanity
repository: https://github.com/sergiyvergun/filter_profanity
issue_tracker: https://github.com/sergiyvergun/filter_profanity/issues

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.15.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

