name: filter_profanity_flutter
description: Dart package to recognize if provided string contains offensive words.

version: 1.0.0
homepage: https://github.com/slaynn/filter_profanity_flutter
repository: https://github.com/slaynn/filter_profanity_flutter
issue_tracker: https://github.com/slaynn/filter_profanity_flutter/issues

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.15.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
